

import { GameItem, Character, HouseTheme, TriviaQuestion, Ingredient, Potion, CreatureDefinition, Stock, VaultUpgrade, WandWood, WandCore, WandColor } from './types';

export const HOUSE_THEMES: Record<string, HouseTheme> = {
  Gryffindor: {
    id: 'Gryffindor',
    primary: 'text-red-500',
    secondary: 'text-yellow-500',
    accentBg: 'bg-red-950/40',
    border: 'border-red-800',
    gradient: 'from-red-950 via-orange-950/40 to-slate-950',
    button: 'bg-red-900/80 hover:bg-red-800 text-yellow-100 border border-red-700'
  },
  Slytherin: {
    id: 'Slytherin',
    primary: 'text-emerald-400',
    secondary: 'text-slate-300',
    accentBg: 'bg-emerald-950/40',
    border: 'border-emerald-800',
    gradient: 'from-emerald-950 via-slate-950/40 to-black',
    button: 'bg-emerald-900/80 hover:bg-emerald-800 text-emerald-100 border border-emerald-700'
  },
  Ravenclaw: {
    id: 'Ravenclaw',
    primary: 'text-blue-400',
    secondary: 'text-sky-200',
    accentBg: 'bg-blue-950/40',
    border: 'border-blue-800',
    gradient: 'from-blue-950 via-indigo-950/40 to-slate-950',
    button: 'bg-blue-900/80 hover:bg-blue-800 text-blue-100 border border-blue-700'
  },
  Hufflepuff: {
    id: 'Hufflepuff',
    primary: 'text-yellow-400',
    secondary: 'text-amber-200',
    accentBg: 'bg-yellow-950/40',
    border: 'border-yellow-800',
    gradient: 'from-yellow-950 via-amber-950/40 to-slate-950',
    button: 'bg-yellow-900/80 hover:bg-yellow-800 text-yellow-100 border border-yellow-700'
  }
};

export const STOCK_MARKET_LIST: Stock[] = [
  { id: 'www', ticker: 'WWW', name: "Weasleys' Wizard Wheezes", description: "High risk, hilarious returns.", basePrice: 50, volatility: 0.25 },
  { id: 'prophet', ticker: 'TDP', name: "The Daily Prophet", description: "Stable dividend, manipulated news.", basePrice: 120, volatility: 0.05 },
  { id: 'nimbus', ticker: 'NBR', name: "Nimbus Racing Broom Co", description: "Cyclical. Watch for new model releases.", basePrice: 250, volatility: 0.15 },
  { id: 'ollivanders', ticker: 'OLL', name: "Ollivanders", description: "The gold standard in wands.", basePrice: 500, volatility: 0.03 },
  { id: 'gringotts', ticker: 'GRN', name: "Gringotts Holdings", description: "Betting on the house. Very safe.", basePrice: 1000, volatility: 0.01 },
  { id: 'zonko', ticker: 'ZNK', name: "Zonko's Joke Shop", description: "Struggling against WWW. High volatility.", basePrice: 30, volatility: 0.4 },
];

export const VAULT_UPGRADES: VaultUpgrade[] = [
  { level: 1, name: 'Standard Vault', cost: 0, capacity: 1000, image: '🗝️', description: 'A basic vault for basic needs.' },
  { level: 2, name: 'Reinforced Door', cost: 1000, capacity: 5000, image: '🚪', description: 'Goblin-forged steel door protection.' },
  { level: 3, name: 'Spell-Sealed', cost: 5000, capacity: 25000, image: '✨', description: 'Protected by ancient protective enchantments.' },
  { level: 4, name: 'Dragon Guarded', cost: 20000, capacity: 100000, image: '🐉', description: 'A Ukrainian Ironbelly sleeps outside.' },
  { level: 5, name: 'Deepest Dungeon', cost: 100000, capacity: 1000000, image: '🏯', description: 'Maximum security. Almost impenetrable.' },
];

export const INITIAL_CHARACTER: Character = {
  name: "Apprentice Wizard",
  house: "Gryffindor",
  gold: 0,
  avatarUrl: "https://picsum.photos/seed/wizard/200/200",
  inventory: [],
  equipped: [],
  customItemImages: {},
  stats: {
    attack: 0,
    defense: 0,
    wins: 0,
    losses: 0,
  },
  matchHistory: [],
  solvedQuestions: [],
  ingredients: {},
  potions: {},
  creatures: [],
  vaultLevel: 1,
  portfolio: {},
  marketPrices: STOCK_MARKET_LIST.reduce((acc, stock) => ({...acc, [stock.id]: stock.basePrice}), {} as Record<string, number>)
};

export const INGREDIENTS_LIST: Ingredient[] = [
  // Basic Ingredients
  { id: 'mandrake', name: 'Mandrake Root', price: 50, description: 'Essential for restorative draughts.', image: '🌱' },
  { id: 'bezoar', name: 'Bezoar', price: 80, description: 'A stone from the stomach of a goat.', image: '🪨' },
  { id: 'lacewing', name: 'Lacewing Flies', price: 30, description: 'Must be stewed for 21 days.', image: '🪰' },
  { id: 'peppermint', name: 'Peppermint', price: 5, description: 'Counter-effect to excessive singing.', image: '🍬' },
  { id: 'ginger', name: 'Ginger Root', price: 8, description: 'Wit-sharpening ingredient.', image: '🫚' },
  { id: 'porcupine', name: 'Porcupine Quills', price: 10, description: 'Handle with care.', image: '🦔' },
  { id: 'flobberworm', name: 'Flobberworm Mucus', price: 15, description: 'Thickens potions.', image: '🟢' },
  { id: 'leech_juice', name: 'Leech Juice', price: 20, description: 'Needed for Polyjuice Potion.', image: '🩸' },
  { id: 'horklump', name: 'Horklump Juice', price: 25, description: 'Healing properties.', image: '🍄' },

  // Intermediate Ingredients
  { id: 'valerian', name: 'Valerian Sprigs', price: 40, description: 'Sedative properties.', image: '🌱' },
  { id: 'knotgrass', name: 'Knotgrass', price: 45, description: 'Ties knots in everything.', image: '🌾' },
  { id: 'shrivelfig', name: 'Shrivelfig', price: 55, description: 'Decanted for shrinking potions.', image: '🟣' },
  { id: 'fluxweed', name: 'Fluxweed', price: 60, description: 'Must be picked at full moon.', image: '🌑' },
  { id: 'wormwood', name: 'Infusion of Wormwood', price: 70, description: 'A very bitter herb.', image: '🌿' },
  { id: 'asphodel', name: 'Powdered Asphodel', price: 90, description: 'Key ingredient for sleeping potions.', image: '🌼' },
  { id: 'moonstone', name: 'Moonstone', price: 100, description: 'Used in love potions and draughts of peace.', image: '💎' },
  { id: 'dittany', name: 'Dittany', price: 100, description: 'Powerful healing herb.', image: '🍃' },

  // Rare Ingredients
  { id: 'unicorn_hair', name: 'Unicorn Hair', price: 120, description: 'Gathered from the Forbidden Forest.', image: '🦄' },
  { id: 'wolfsbane_plant', name: 'Wolfsbane', price: 130, description: 'Also known as aconite or monkshood.', image: '🐺' },
  { id: 'dragon_liver', name: 'Dragon Liver', price: 150, description: 'Highly potent and volatile.', image: '🐉' },
  { id: 'sopophorous', name: 'Sopophorous Bean', price: 180, description: 'Juice is extracted by crushing, not cutting.', image: '🫘' },
  { id: 'boomslang', name: 'Boomslang Skin', price: 200, description: 'Shredded skin of a poisonous snake.', image: '🐍' },
  { id: 'horn_of_bicorn', name: 'Horn of Bicorn', price: 250, description: 'Extremely rare ingredient.', image: '🦄' },
  { id: 'ashwinder', name: 'Ashwinder Egg', price: 300, description: 'Frozen immediately to prevent combustion.', image: '🥚' }
];

export const POTION_RECIPES: Potion[] = [
  // Basic Potions
  { 
    id: 'cure_boils', 
    name: 'Cure for Boils', 
    description: 'A simple potion to cure boils. Watch the heat!', 
    sellPrice: 150, 
    image: '⚗️',
    ingredients: ['mandrake', 'bezoar'],
    difficulty: 10
  },
  { 
    id: 'pepperup', 
    name: 'Pepperup Potion', 
    description: 'Cures the common cold. Steam from ears side-effect.', 
    sellPrice: 400, 
    image: '😤',
    ingredients: ['horn_of_bicorn', 'mandrake', 'ginger'],
    difficulty: 30
  },
  { 
    id: 'confusing', 
    name: 'Confusing Concoction', 
    description: 'Causes confusion and recklessness.', 
    sellPrice: 350, 
    image: '😵',
    ingredients: ['leech_juice', 'horklump'],
    difficulty: 35
  },
  { 
    id: 'essence_dittany', 
    name: 'Essence of Dittany', 
    description: 'Powerful healing agent for wounds.', 
    sellPrice: 500, 
    image: '🩹',
    ingredients: ['dittany', 'leech_juice'],
    difficulty: 45
  },
  
  // Intermediate Potions
  { 
    id: 'forgetfulness', 
    name: 'Forgetfulness Potion', 
    description: 'Causes an unknown degree of memory loss.', 
    sellPrice: 250, 
    image: '🧪',
    ingredients: ['mandrake', 'unicorn_hair'],
    difficulty: 25
  },
  { 
    id: 'sleeping', 
    name: 'Sleeping Draught', 
    description: 'Induces immediate, deep sleep.', 
    sellPrice: 400, 
    image: '💤',
    ingredients: ['mandrake', 'lacewing', 'unicorn_hair'],
    difficulty: 40
  },
  { 
    id: 'ageing', 
    name: 'Ageing Potion', 
    description: 'Causes the drinker to age temporarily.', 
    sellPrice: 600, 
    image: '👴',
    ingredients: ['boomslang', 'leech_juice'],
    difficulty: 50
  },
  { 
    id: 'skele_gro', 
    name: 'Skele-Gro', 
    description: 'Regrows bones. Tastes awful.', 
    sellPrice: 900, 
    image: '🦴',
    ingredients: ['flobberworm', 'shrivelfig', 'porcupine'],
    difficulty: 60
  },
  { 
    id: 'peace', 
    name: 'Draught of Peace', 
    description: 'Relieves anxiety and agitation.', 
    sellPrice: 1000, 
    image: '😌',
    ingredients: ['moonstone', 'valerian', 'porcupine'],
    difficulty: 70
  },

  // Advanced Potions
  { 
    id: 'polyjuice_simple', 
    name: 'Polyjuice Potion (Weak)', 
    description: 'Allows the drinker to assume the form of another for a short time.', 
    sellPrice: 1200, 
    image: '👥',
    ingredients: ['lacewing', 'boomslang', 'dragon_liver'],
    difficulty: 75
  },
  { 
    id: 'polyjuice', 
    name: 'Polyjuice Potion (Strong)', 
    description: 'Allows the drinker to assume the form of another.', 
    sellPrice: 2500, 
    image: '👥',
    ingredients: ['lacewing', 'boomslang', 'horn_of_bicorn'],
    difficulty: 80
  },
  { 
    id: 'draught_living_death', 
    name: 'Draught of Living Death', 
    description: 'A sleeping potion so powerful it mimics death.', 
    sellPrice: 2800, 
    image: '💀',
    ingredients: ['asphodel', 'wormwood', 'sopophorous'],
    difficulty: 85
  },
  { 
    id: 'wolfsbane', 
    name: 'Wolfsbane Potion', 
    description: 'Relieves symptoms of lycanthropy. Does not cure.', 
    sellPrice: 3500, 
    image: '🌕',
    ingredients: ['wolfsbane_plant', 'moonstone', 'valerian'],
    difficulty: 95
  },
  { 
    id: 'veritaserum', 
    name: 'Veritaserum', 
    description: 'Forces the drinker to tell the truth.', 
    sellPrice: 4500, 
    image: '👁️',
    ingredients: ['moonstone', 'sopophorous', 'unicorn_hair'],
    difficulty: 90
  },
  { 
    id: 'amortentia', 
    name: 'Amortentia', 
    description: 'The most powerful love potion in the world.', 
    sellPrice: 2000, 
    image: '💖',
    ingredients: ['moonstone', 'ashwinder', 'dragon_liver'],
    difficulty: 60
  },
  { 
    id: 'felix', 
    name: 'Felix Felicis', 
    description: 'Liquid Luck. Very dangerous to brew.', 
    sellPrice: 5000, 
    image: '🍀',
    ingredients: ['ashwinder', 'moonstone', 'dragon_liver', 'unicorn_hair'],
    difficulty: 95
  },
  { 
    id: 'elixir_life',
    name: 'Elixir of Life',
    description: 'Extends life. Requires extremely rare ingredients.',
    sellPrice: 10000,
    image: '🏺',
    ingredients: ['ashwinder', 'sopophorous', 'horn_of_bicorn'],
    difficulty: 99
  }
];

export const CREATURE_SHOP: CreatureDefinition[] = [
    // Original Creatures
    { id: 'owl_common', species: 'Barn Owl', name: 'Barn Owl', description: 'Reliable mail carrier. Occasionally finds loose change.', price: 200, image: '🦉', bonusType: 'GOLD_FINDER', bonusValue: 5 },
    { id: 'toad', species: 'Common Toad', name: 'Toad', description: 'Not very popular, but loyal. Slime aids defense.', price: 50, image: '🐸', bonusType: 'DEFENSE_BOOST', bonusValue: 5 },
    { id: 'cat_kneazle', species: 'Kneazle', name: 'Kneazle', description: 'Intelligent cat-like creature. Good at sniffing out bargains.', price: 300, image: '🐈', bonusType: 'DISCOUNT', bonusValue: 0.05 },
    { id: 'hippogriff', species: 'Hippogriff', name: 'Hippogriff', description: 'Proud and powerful. Intimidates foes.', price: 1000, image: '🦅', bonusType: 'ATTACK_BOOST', bonusValue: 10 },
    { id: 'dragon_hatchling', species: 'Dragon Hatchling', name: 'Norbert', description: 'Illegal, dangerous, and adorable. Hoards gold.', price: 5000, image: '🐲', bonusType: 'GOLD_FINDER', bonusValue: 50 },
    { id: 'niffler', species: 'Niffler', name: 'Niffler', description: 'Attracted to shiny things. Excellent treasure hunter.', price: 800, image: '🦡', bonusType: 'GOLD_FINDER', bonusValue: 20 },
    { id: 'phoenix_chick', species: 'Phoenix Chick', name: 'Fawkes Jr.', description: 'Immortal and loyal. Healing tears boost defense.', price: 10000, image: '🔥', bonusType: 'DEFENSE_BOOST', bonusValue: 50 },

    // New Creatures
    { id: 'puffskein', species: 'Pygmy Puff', name: 'Pygmy Puff', description: 'Cute, fluffy, and comes in various shades of pink and purple.', price: 150, image: '🧶', bonusType: 'DEFENSE_BOOST', bonusValue: 2 },
    { id: 'bowtruckle', species: 'Bowtruckle', name: 'Bowtruckle', description: 'Tree guardian. Good at picking locks (finding discounts).', price: 450, image: '🌱', bonusType: 'DISCOUNT', bonusValue: 0.02 },
    { id: 'demiguise', species: 'Demiguise', name: 'Demiguise', description: 'Can turn invisible. Enhances defensive tactics.', price: 1200, image: '🐒', bonusType: 'DEFENSE_BOOST', bonusValue: 15 },
    { id: 'occamy', species: 'Occamy', name: 'Occamy', description: 'Choranaptyxic. Grows to fill space. Aggressive.', price: 2500, image: '🐍', bonusType: 'ATTACK_BOOST', bonusValue: 25 },
    { id: 'thestral', species: 'Thestral', name: 'Thestral', description: 'Invisible to those who haven\'t seen death. Unnerving.', price: 1800, image: '🐎', bonusType: 'ATTACK_BOOST', bonusValue: 18 },
    { id: 'mooncalf', species: 'Mooncalf', name: 'Mooncalf', description: 'Dances by moonlight. Its dung makes magical plants grow.', price: 600, image: '🐂', bonusType: 'GOLD_FINDER', bonusValue: 8 },
    { id: 'fwooper', species: 'Fwooper', name: 'Fwooper', description: 'Brightly colored bird. Its song will drive you mad.', price: 900, image: '🦜', bonusType: 'ATTACK_BOOST', bonusValue: 12 },
    { id: 'diricawl', species: 'Diricawl', name: 'Diricawl', description: 'Flightless bird that can vanish. Hard to catch.', price: 750, image: '🐦', bonusType: 'DEFENSE_BOOST', bonusValue: 10 },
    { id: 'ghoul', species: 'Ghoul', name: 'Attic Ghoul', description: 'Noisy and messy, but keeps unwanted guests away.', price: 100, image: '🧟', bonusType: 'DEFENSE_BOOST', bonusValue: 3 },
    { id: 'gnome', species: 'Garden Gnome', name: 'Gnome', description: 'Pest. Might dig up a knut or two.', price: 25, image: '🥔', bonusType: 'GOLD_FINDER', bonusValue: 1 },
    { id: 'fire_crab', species: 'Fire Crab', name: 'Fire Crab', description: 'Looks like a jeweled tortoise. Shoots fire.', price: 1100, image: '🦀', bonusType: 'ATTACK_BOOST', bonusValue: 14 },
    { id: 'salamander', species: 'Fire Dwelling Salamander', name: 'Salamander', description: 'Lives in flames. Hot to handle.', price: 550, image: '🦎', bonusType: 'ATTACK_BOOST', bonusValue: 8 },
    { id: 'streeler', species: 'Streeler', name: 'Streeler', description: 'Giant snail that leaves a poisonous trail.', price: 650, image: '🐌', bonusType: 'DEFENSE_BOOST', bonusValue: 8 },
    { id: 'jarvey', species: 'Jarvey', name: 'Jarvey', description: 'Looks like a ferret. Can talk (mostly insults).', price: 400, image: '🦦', bonusType: 'ATTACK_BOOST', bonusValue: 5 },
    { id: 'jobberknoll', species: 'Jobberknoll', name: 'Jobberknoll', description: 'Silent until death. Feathers used in truth serums.', price: 500, image: '🐦‍⬛', bonusType: 'DISCOUNT', bonusValue: 0.03 },
    { id: 'knarl', species: 'Knarl', name: 'Knarl', description: 'Suspicious hedgehog-like creature.', price: 250, image: '🦔', bonusType: 'DEFENSE_BOOST', bonusValue: 4 },
    { id: 'moke', species: 'Moke', name: 'Moke', description: 'Shrinks at will. Hides in small places.', price: 350, image: '🦎', bonusType: 'DEFENSE_BOOST', bonusValue: 6 },
    { id: 'plimpy', species: 'Plimpy', name: 'Plimpy', description: 'Spherical fish. Nibbles on toes.', price: 120, image: '🐟', bonusType: 'ATTACK_BOOST', bonusValue: 2 },
    { id: 'billywig', species: 'Billywig', name: 'Billywig', description: 'Blue insect. Sting causes levitation.', price: 850, image: '🐝', bonusType: 'GOLD_FINDER', bonusValue: 10 },
    { id: 'blast_ended_skrewt', species: 'Blast-Ended Skrewt', name: 'Skrewt', description: 'Illegal hybrid. Explodes from the rear. Very dangerous.', price: 2200, image: '🦂', bonusType: 'ATTACK_BOOST', bonusValue: 30 }
];

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  // EXISTING
  { question: "What is the core of the Elder Wand?", options: ["Phoenix Feather", "Dragon Heartstring", "Thestral Tail Hair", "Unicorn Hair"], correctAnswer: 2 },
  { question: "Which Potion is known as 'Liquid Luck'?", options: ["Amortentia", "Polyjuice Potion", "Veritaserum", "Felix Felicis"], correctAnswer: 3 },
  
  // CHARACTERS & BIOGRAPHY
  { question: "What is Dumbledore's full name?", options: ["Albus Brian Percival Wulfric Dumbledore", "Albus Percival Wulfric Brian Dumbledore", "Albus Wulfric Percival Brian Dumbledore", "Albus Percival Brian Wulfric Dumbledore"], correctAnswer: 1 },
  { question: "Who is the Half-Blood Prince?", options: ["Tom Riddle", "Harry Potter", "Severus Snape", "Sirius Black"], correctAnswer: 2 },
  { question: "What is Hermionie Granger's middle name?", options: ["Jane", "Jean", "Joan", "June"], correctAnswer: 1 },
  { question: "Who was the first Peverell brother to die?", options: ["Antioch", "Cadmus", "Ignotus", "Marvolo"], correctAnswer: 0 },
  { question: "What is the name of Filch's cat?", options: ["Mrs. Norris", "Crookshanks", "Fang", "Ripper"], correctAnswer: 0 },
  { question: "Who killed Bellatrix Lestrange?", options: ["Harry Potter", "Ginny Weasley", "Hermione Granger", "Molly Weasley"], correctAnswer: 3 },
  { question: "What is the name of Hagrid's three-headed dog?", options: ["Fluffy", "Fang", "Norbert", "Aragog"], correctAnswer: 0 },
  { question: "Who was the master of the Elder Wand before Dumbledore?", options: ["Voldemort", "Grindelwald", "Gregorovitch", "Snape"], correctAnswer: 1 },
  { question: "What is the name of the poltergeist at Hogwarts?", options: ["Peeves", "Nearly Headless Nick", "The Bloody Baron", "The Fat Friar"], correctAnswer: 0 },
  { question: "Who teaches History of Magic?", options: ["Professor Flitwick", "Professor Binns", "Professor Vector", "Professor Sinistra"], correctAnswer: 1 },
  { question: "What is the name of Voldemort's snake?", options: ["Basilisk", "Nagini", "Salazar", "Serpens"], correctAnswer: 1 },
  { question: "Who is the ghost of Ravenclaw Tower?", options: ["The Fat Friar", "The Bloody Baron", "The Grey Lady", "Nearly Headless Nick"], correctAnswer: 2 },
  { question: "What is the name of Harry's owl?", options: ["Errol", "Pigwidgeon", "Hedwig", "Hermes"], correctAnswer: 2 },
  { question: "Who put Harry's name in the Goblet of Fire?", options: ["Igor Karkaroff", "Barty Crouch Jr.", "Ludo Bagman", "Severus Snape"], correctAnswer: 1 },
  { question: "What is the name of the Weasley family home?", options: ["The Burrow", "Shell Cottage", "Grimmauld Place", "Spinner's End"], correctAnswer: 0 },
  { question: "Who is the Head of Hufflepuff House?", options: ["Professor Sprout", "Professor Flitwick", "Professor McGonagall", "Professor Slughorn"], correctAnswer: 0 },
  { question: "What is the name of Draco Malfoy's son?", options: ["Scorpius", "Lucius", "Abraxas", "Orion"], correctAnswer: 0 },
  { question: "Who was the first prisoner to escape Azkaban without help?", options: ["Bellatrix Lestrange", "Sirius Black", "Barty Crouch Jr.", "Antonin Dolohov"], correctAnswer: 1 },
  { question: "What is the name of Tonks and Lupin's son?", options: ["Teddy", "James", "Albus", "Remus"], correctAnswer: 0 },
  { question: "Who is the editor of The Quibbler?", options: ["Rita Skeeter", "Xenophilius Lovegood", "Barnabas Cuffe", "Luna Lovegood"], correctAnswer: 1 },

  // SPELLS & MAGIC
  { question: "What is the incantation for the Disarming Charm?", options: ["Stupefy", "Expelliarmus", "Protego", "Accio"], correctAnswer: 1 },
  { question: "Which spell unlocks doors?", options: ["Alohomora", "Colloportus", "Aparecium", "Dissendium"], correctAnswer: 0 },
  { question: "What does the spell 'Sectumsempra' do?", options: ["Heals wounds", "Causes deep cuts", "Disarms opponent", "Summons snakes"], correctAnswer: 1 },
  { question: "What spell summons objects to the caster?", options: ["Accio", "Depulso", "Wingardium Leviosa", "Locomotor"], correctAnswer: 0 },
  { question: "Which curse controls the victim?", options: ["Cruciatus", "Imperius", "Avada Kedavra", "Legilimens"], correctAnswer: 1 },
  { question: "What is the counter-spell to 'Lumos'?", options: ["Nox", "Obscuro", "Finite", "Extinguo"], correctAnswer: 0 },
  { question: "What spell repels Dementors?", options: ["Riddikulus", "Expecto Patronum", "Lumos Solem", "Protego Totalum"], correctAnswer: 1 },
  { question: "What does 'Wingardium Leviosa' do?", options: ["Levitates objects", "Creates fire", "Unlocks doors", "Freezes water"], correctAnswer: 0 },
  { question: "Which spell is used to erase memories?", options: ["Confundo", "Obliviate", "Stupefy", "Muffliato"], correctAnswer: 1 },
  { question: "What does the 'Morsmordre' spell conjure?", options: ["The Dark Mark", "A Patronus", "Fiendfyre", "A shield"], correctAnswer: 0 },
  { question: "What spell reveals hidden messages?", options: ["Aparecium", "Homenum Revelio", "Specialis Revelio", "Flagrate"], correctAnswer: 0 },
  { question: "What spell is used to fix Harry's glasses?", options: ["Reparo", "Episkey", "Tergeo", "Scourgify"], correctAnswer: 0 },
  { question: "What is the incantation for the Killing Curse?", options: ["Avada Kedavra", "Crucio", "Imperio", "Morsmordre"], correctAnswer: 0 },
  { question: "Which spell creates water?", options: ["Incendio", "Aguamenti", "Glacius", "Diffindo"], correctAnswer: 1 },
  { question: "What spell did Hermione use to free Sirius Black?", options: ["Alohomora", "Bombarda", "Relashio", "Bombarda Maxima"], correctAnswer: 1 }, /* Movie canon mostly, but acceptable */
  { question: "What spell creates a duplicate of an object?", options: ["Geminio", "Engorgio", "Reducio", "Reparo"], correctAnswer: 0 },
  { question: "What spell turns a Boggart into something funny?", options: ["Riddikulus", "Expecto Patronum", "Confundo", "Stupefy"], correctAnswer: 0 },
  { question: "What spell silences a target?", options: ["Silencio", "Muffliato", "Quietus", "Langlock"], correctAnswer: 0 },
  { question: "What spell protects against Legilimency?", options: ["Occlumency", "Protego", "Salvio Hexia", "Repello Muggletum"], correctAnswer: 0 },
  { question: "What spell makes objects larger?", options: ["Reducio", "Engorgio", "Sonorus", "Amplificatum"], correctAnswer: 1 },

  // OBJECTS & ARTIFACTS
  { question: "How many Horcruxes did Voldemort intentionally create?", options: ["5", "6", "7", "8"], correctAnswer: 1 },
  { question: "What object was NOT a Horcrux?", options: ["The Sword of Gryffindor", "Hufflepuff's Cup", "Ravenclaw's Diadem", "Slytherin's Locket"], correctAnswer: 0 },
  { question: "Who destroyed the Hufflepuff Cup Horcrux?", options: ["Harry", "Ron", "Hermione", "Neville"], correctAnswer: 2 },
  { question: "What is the number of Harry's vault at Gringotts?", options: ["687", "711", "713", "394"], correctAnswer: 0 },
  { question: "Which Deathly Hallow is an invisibility cloak?", options: ["The Elder Wand", "The Resurrection Stone", "The Cloak of Invisibility", "The Philosophers Stone"], correctAnswer: 2 },
  { question: "What sits atop the Ravenclaw Diadem?", options: ["A raven", "A sapphire", "A riddle", "Nothing"], correctAnswer: 1 },
  { question: "What unlocks the Marauder's Map?", options: ["I solemnly swear that I am up to no good", "Mischief Managed", "Alohomora", "Open Sesame"], correctAnswer: 0 },
  { question: "Who gave Harry his first broomstick?", options: ["Sirius Black", "Professor McGonagall", "Hagrid", "Dumbledore"], correctAnswer: 1 },
  { question: "What connects the Floo Network?", options: ["Mirrors", "Fireplaces", "Toilets", "Portkeys"], correctAnswer: 1 },
  { question: "What kind of wood is Harry's wand made of?", options: ["Yew", "Holly", "Vine", "Oak"], correctAnswer: 1 },
  { question: "What is the core of Harry's wand?", options: ["Dragon Heartstring", "Unicorn Hair", "Phoenix Feather", "Veela Hair"], correctAnswer: 2 },
  { question: "How many balls are used in a game of Quidditch?", options: ["2", "3", "4", "5"], correctAnswer: 2 },
  { question: "What object selects the champions for the Triwizard Tournament?", options: ["The Sorting Hat", "The Goblet of Fire", "The Sword of Gryffindor", "The Pensieve"], correctAnswer: 1 },
  { question: "What does the Remembrall turn red for?", options: ["Danger", "Lies", "Forgetfulness", "Enemies"], correctAnswer: 2 },
  { question: "Who originally owned the Invisibility Cloak given to Harry?", options: ["James Potter", "Sirius Black", "Dumbledore", "Snape"], correctAnswer: 0 },
  { question: "What is the name of the magical map of Hogwarts?", options: ["The Marauder's Map", "The Hogwarts Map", "The Seeker's Map", "The Castle Chart"], correctAnswer: 0 },
  { question: "What are the sweets that make you sick to get out of class?", options: ["Skiving Snackboxes", "Canary Creams", "Ton-Tongue Toffee", "Puking Pastilles"], correctAnswer: 0 },
  { question: "What is inside the Snitch?", options: ["The Resurrection Stone", "A ring", "A bean", "Nothing"], correctAnswer: 0 },
  { question: "How much is a Galleon worth in Sickles?", options: ["10", "17", "29", "100"], correctAnswer: 1 },
  { question: "How much is a Sickle worth in Knuts?", options: ["17", "21", "29", "50"], correctAnswer: 2 },

  // CREATURES
  { question: "What creature pulls the Hogwarts carriages?", options: ["Hippogriffs", "Thestrals", "Unicorns", "Centaurs"], correctAnswer: 1 },
  { question: "What is a Dementor's kiss?", options: ["It kills you", "It sucks out your soul", "It freezes you", "It makes you sad"], correctAnswer: 1 },
  { question: "What do dragons guard at Gringotts?", options: ["The entrance", "The high security vaults", "The goblins", "The lobby"], correctAnswer: 1 },
  { question: "What is Aragog?", options: ["A werewolf", "A giant", "An Acromantula", "A Basilisk"], correctAnswer: 2 },
  { question: "What creature can turn into your worst fear?", options: ["Dementor", "Boggart", "Banshee", "Poltergeist"], correctAnswer: 1 },
  { question: "What is the name of the hippogriff in Prisoner of Azkaban?", options: ["Witherwings", "Buckbeak", "Stormswift", "Fleetfoot"], correctAnswer: 1 },
  { question: "What are house-elves freed with?", options: ["Gold", "Clothes", "Food", "Spells"], correctAnswer: 1 },
  { question: "What does a Phoenix do when it dies?", options: ["It rots", "It turns to stone", "It bursts into flame and is reborn", "It disappears"], correctAnswer: 2 },
  { question: "What is the only known antidote to Basilisk venom?", options: ["Phoenix tears", "Mandrake juice", "Bezoar", "Unicorn blood"], correctAnswer: 0 },
  { question: "What creature is 'Norbert'?", options: ["A Norwegian Ridgeback", "A Hungarian Horntail", "A Swedish Short-Snout", "A Chinese Fireball"], correctAnswer: 0 },
  { question: "What is Grawp?", options: ["A troll", "A goblin", "A giant", "A centaur"], correctAnswer: 2 },
  { question: "What magical creature is Fluffy?", options: ["A Cerberus", "A Grim", "A Hellhound", "A Chimera"], correctAnswer: 0 },
  { question: "Which creature feeds on human brains?", options: ["Lethifold", "Pogrebin", "Nogtail", "No such creature"], correctAnswer: 0 }, /* Lethifolds suffocate, but there's a brain room. Wait, tricky. Actually, it's not a common creature. Let's swap.*/
  { question: "What attracts a Niffler?", options: ["Food", "Shiny things", "Music", "Heat"], correctAnswer: 1 },
  { question: "What is a Mandrake's cry known to do?", options: ["Heal wounds", "Kill or knock out", "Break glass", "Summon spirits"], correctAnswer: 1 },
  { question: "What creature is represented by the Ravenclaw mascot?", options: ["Raven", "Eagle", "Hawk", "Crow"], correctAnswer: 1 },
  { question: "What animal is the symbol of Hufflepuff?", options: ["Bear", "Badger", "Beaver", "Boar"], correctAnswer: 1 },
  { question: "What is a Bowtruckle?", options: ["A tree guardian", "A water demon", "A rock spirit", "A fire lizard"], correctAnswer: 0 },
  { question: "What did Ginny Weasley name her Pygmy Puff?", options: ["Arnold", "Arthur", "Archie", "Albus"], correctAnswer: 0 },
  { question: "What breed of dragon did Harry face in the Triwizard Tournament?", options: ["Chinese Fireball", "Swedish Short-Snout", "Hungarian Horntail", "Common Welsh Green"], correctAnswer: 2 },

  // POTIONS & INGREDIENTS
  { question: "What are the effects of Polyjuice Potion?", options: ["Invisibility", "Super strength", "Change appearance", "Read minds"], correctAnswer: 2 },
  { question: "What is a bezoar found in?", options: ["A goat's stomach", "A dragon's liver", "A mandrake root", "A unicorn's horn"], correctAnswer: 0 },
  { question: "What potion forces the drinker to tell the truth?", options: ["Felix Felicis", "Amortentia", "Veritaserum", "Polyjuice Potion"], correctAnswer: 2 },
  { question: "What does Amortentia smell like?", options: ["Rotten eggs", "Different to everyone", "Roses", "Chocolate"], correctAnswer: 1 },
  { question: "What is the main ingredient in Skele-Gro?", options: ["Pufferfish eyes", "Chinese Chomping Cabbage", "Flobberworm Mucus", "Unknown"], correctAnswer: 3 }, /* Actually mentioned as unpalatable, exact recipe vague in books */
  { question: "What potion did Harry win from Slughorn?", options: ["Veritaserum", "Felix Felicis", "Polyjuice Potion", "Draught of Living Death"], correctAnswer: 1 },
  { question: "What happens if you drink Unicorn blood?", options: ["You die instantly", "You become immortal but cursed", "You turn into a unicorn", "You fall asleep"], correctAnswer: 1 },
  { question: "What are the ingredients of the Draught of Living Death?", options: ["Asphodel and Wormwood", "Mandrake and Bezoar", "Moonstone and Hellebore", "Monkshood and Wolfsbane"], correctAnswer: 0 },
  { question: "Who took the Wolfsbane Potion?", options: ["Sirius Black", "Remus Lupin", "Fenrir Greyback", "Peter Pettigrew"], correctAnswer: 1 },
  { question: "What color is the Polyjuice Potion when Harry drinks it?", options: ["Gold", "Muddy Brown", "Silver", "Green"], correctAnswer: 0 }, /* Wait, for Harry it was gold? No, Goyle was khaki, Crabbe was dark brown. Harry's was 'bright gold' in movie? In book, for Goyle it was khaki. For Harry turning into Goyle? The question is vague. Let's replace. */
  { question: "What potion cures boils?", options: ["Cure for Boils", "Deflating Draught", "Swelling Solution", "Pepperup Potion"], correctAnswer: 0 },
  { question: "What plant is used so you can breathe underwater?", options: ["Gillyweed", "Knotgrass", "Fluxweed", "Mandrake"], correctAnswer: 0 },
  { question: "What is the antidote to a love potion?", options: ["Hate Potion", "Wiggenweld Potion", "Dr. Ubbly's Oblivious Unction", "Love Potion Antidote"], correctAnswer: 3 }, /* Specific name elusive */
  { question: "Where can you find a Bezoar?", options: ["Apothecary", "Cupboard", "Stomach of a goat", "Forest"], correctAnswer: 2 },
  { question: "What ingredient must be picked at the full moon for Polyjuice Potion?", options: ["Fluxweed", "Knotgrass", "Lacewing Flies", "Leech Juice"], correctAnswer: 0 },
  { question: "What is Monkshood also known as?", options: ["Wolfsbane", "Wormwood", "Willow", "Wattle"], correctAnswer: 0 },
  { question: "How long does Felix Felicis take to brew?", options: ["1 month", "3 months", "6 months", "1 year"], correctAnswer: 2 },
  { question: "What potion makes you look like your friends?", options: ["Polyjuice Potion", "Essence of Dittany", "Mandrake Draught", "Elixir of Life"], correctAnswer: 0 },
  { question: "Which potion causes steam to come out of the drinker's ears?", options: ["Pepperup Potion", "Skele-Gro", "Polyjuice Potion", "Veritaserum"], correctAnswer: 0 },
  { question: "Who is the Potions Master in Harry's first year?", options: ["Slughorn", "Snape", "Sprout", "Flitwick"], correctAnswer: 1 },

  // LOCATIONS
  { question: "Where is the entrance to the Chamber of Secrets?", options: ["The Great Hall", "The Dungeon", "Moaning Myrtle's Bathroom", "The Astronomy Tower"], correctAnswer: 2 },
  { question: "What platform does the Hogwarts Express depart from?", options: ["9", "10", "9 3/4", "11"], correctAnswer: 2 },
  { question: "Where is the Order of the Phoenix headquarters?", options: ["Godric's Hollow", "12 Grimmauld Place", "The Burrow", "Shell Cottage"], correctAnswer: 1 },
  { question: "Where did Harry live with the Dursleys?", options: ["12 Grimmauld Place", "4 Privet Drive", "Godric's Hollow", "Spinner's End"], correctAnswer: 1 },
  { question: "What village is near Hogwarts?", options: ["Hogsmeade", "Godric's Hollow", "Ottery St. Catchpole", "Little Hangleton"], correctAnswer: 0 },
  { question: "Where does Vernon Dursley work?", options: ["Grunnings", "Gringotts", "The Ministry", "A Post Office"], correctAnswer: 0 },
  { question: "What is the name of the pub in Hogsmeade?", options: ["The Leaky Cauldron", "The Three Broomsticks", "The Hog's Head", "The White Wyvern"], correctAnswer: 1 },
  { question: "Where does Harry buy his school supplies?", options: ["Hogsmeade", "Diagon Alley", "Knockturn Alley", "Godric's Hollow"], correctAnswer: 1 },
  { question: "What is the name of the wizard prison?", options: ["Nurmengard", "Azkaban", "The Raft", "Alcatraz"], correctAnswer: 1 },
  { question: "Where is the Slytherin Common Room located?", options: ["The Dungeons", "The Astronomy Tower", "The Ground Floor", "The West Tower"], correctAnswer: 0 },
  { question: "Where is the Ravenclaw Common Room?", options: ["The Dungeons", "A Tower", "Near the Kitchens", "The Great Hall"], correctAnswer: 1 },
  { question: "Where is the Hufflepuff Common Room?", options: ["Near the Kitchens", "The Dungeons", "A Tower", "The Grounds"], correctAnswer: 0 },
  { question: "What street is the Leaky Cauldron on?", options: ["Charing Cross Road", "Privet Drive", "Grimmauld Place", "Diagon Alley"], correctAnswer: 0 },
  { question: "Where did Voldemort hide the Diadem?", options: ["The Room of Requirement", "The Chamber of Secrets", "Gringotts", "The Forbidden Forest"], correctAnswer: 0 },
  { question: "Where did Voldemort hide the Locket?", options: ["A Cave", "Gringotts", "Hogwarts", "Little Hangleton"], correctAnswer: 0 },
  { question: "Where did Voldemort hide the Cup?", options: ["A Cave", "Gringotts", "Hogwarts", "Malfoy Manor"], correctAnswer: 1 },
  { question: "What is the name of the sweet shop in Hogsmeade?", options: ["Zonko's", "Honeydukes", "Scrivenshaft's", "The Three Broomsticks"], correctAnswer: 1 },
  { question: "Where did Harry find the Sword of Gryffindor in Book 7?", options: ["A frozen pool", "The Sorting Hat", "Gringotts", "Dumbledore's Office"], correctAnswer: 0 },
  { question: "What is the Room of Requirement also known as?", options: ["The Come and Go Room", "The Hidden Room", "The Secret Room", "The Lost Room"], correctAnswer: 0 },
  { question: "Where is the Hospital Wing located?", options: ["Ground Floor", "First Floor", "Second Floor", "Third Floor"], correctAnswer: 1 }, /* Varies slightly in media, but usually 1st */

  // QUOTES & EVENTS
  { question: "Who said 'After all this time? Always.'?", options: ["Dumbledore", "Snape", "Harry", "Lily"], correctAnswer: 1 },
  { question: "Who said 'I solemnly swear that I am up to no good'?", options: ["Fred & George", "The Marauders", "Harry", "Ron"], correctAnswer: 1 },
  { question: "Who opened the Chamber of Secrets the first time?", options: ["Tom Riddle", "Hagrid", "Ginny Weasley", "Draco Malfoy"], correctAnswer: 0 },
  { question: "Who saved Harry from the Dementors in Book 3?", options: ["Dumbledore", "Sirius Black", "Harry himself", "James Potter"], correctAnswer: 2 },
  { question: "How many points is the Golden Snitch worth?", options: ["50", "100", "150", "200"], correctAnswer: 2 },
  { question: "Who died in the Triwizard Tournament?", options: ["Cedric Diggory", "Viktor Krum", "Fleur Delacour", "Harry Potter"], correctAnswer: 0 },
  { question: "Who killed Dumbledore?", options: ["Voldemort", "Draco Malfoy", "Severus Snape", "Bellatrix Lestrange"], correctAnswer: 2 },
  { question: "Who gave Harry the Marauder's Map?", options: ["Remus Lupin", "Sirius Black", "Fred and George Weasley", "James Potter"], correctAnswer: 2 },
  { question: "Who is the Half-Blood Prince?", options: ["Snape", "Harry", "Voldemort", "Slughorn"], correctAnswer: 0 },
  { question: "What year was the Battle of Hogwarts?", options: ["1997", "1998", "1999", "2000"], correctAnswer: 1 },
  { question: "Who won the House Cup in Harry's first year?", options: ["Slytherin", "Ravenclaw", "Hufflepuff", "Gryffindor"], correctAnswer: 3 },
  { question: "Who destroyed the diary Horcrux?", options: ["Harry Potter", "Ron Weasley", "Hermione Granger", "Ginny Weasley"], correctAnswer: 0 },
  { question: "Who did Hermione go to the Yule Ball with?", options: ["Harry Potter", "Ron Weasley", "Viktor Krum", "Neville Longbottom"], correctAnswer: 2 },
  { question: "Who poses as Mad-Eye Moody in Book 4?", options: ["Barty Crouch Sr.", "Barty Crouch Jr.", "Peter Pettigrew", "Igor Karkaroff"], correctAnswer: 1 },
  { question: "Who teaches Defence Against the Dark Arts in Book 5?", options: ["Lupin", "Lockhart", "Umbridge", "Moody"], correctAnswer: 2 },
  { question: "Who kills Nagini?", options: ["Harry", "Ron", "Hermione", "Neville"], correctAnswer: 3 },
  { question: "How many presents did Dudley get on his 11th birthday?", options: ["35", "36", "37", "38"], correctAnswer: 1 },
  { question: "What is the password to the Prefect's Bathroom?", options: ["Pine Fresh", "Caput Draconis", "Pig Snout", "Wattlebird"], correctAnswer: 0 },
  { question: "Who is the Gryffindor Ghost?", options: ["Nearly Headless Nick", "The Bloody Baron", "The Fat Friar", "The Grey Lady"], correctAnswer: 0 },
  { question: "Who referee'd the Quidditch World Cup Final?", options: ["Ludo Bagman", "Hassan Mostafa", "Madam Hooch", "Barty Crouch"], correctAnswer: 1 },

  // MISCELLANEOUS
  { question: "What organization did Hermione start?", options: ["D.A.", "S.P.E.W.", "The Order", "Slug Club"], correctAnswer: 1 },
  { question: "What does S.P.E.W. stand for?", options: ["Society for the Promotion of Elfish Welfare", "Society for the Protection of Elfish Welfare", "Society for the Prevention of Elfish Work", "Save Poor Elfish Workers"], correctAnswer: 0 },
  { question: "What is Harry's Patronus?", options: ["Stag", "Doe", "Otter", "Terrier"], correctAnswer: 0 },
  { question: "What is Hermione's Patronus?", options: ["Stag", "Doe", "Otter", "Cat"], correctAnswer: 2 },
  { question: "What is Ron's Patronus?", options: ["Jack Russell Terrier", "Rat", "Owl", "Weasel"], correctAnswer: 0 },
  { question: "What is Luna's Patronus?", options: ["Hare", "Rabbit", "Cat", "Horse"], correctAnswer: 0 },
  { question: "What is Ginny's Patronus?", options: ["Horse", "Cat", "Otter", "Stag"], correctAnswer: 0 },
  { question: "What is Snape's Patronus?", options: ["Stag", "Doe", "Lily", "Snake"], correctAnswer: 1 },
  { question: "What is Dumbledore's Patronus?", options: ["Phoenix", "Eagle", "Lion", "Goat"], correctAnswer: 0 },
  { question: "What is McGonagall's Patronus?", options: ["Cat", "Lion", "Eagle", "Owl"], correctAnswer: 0 },
  { question: "What is Umbridge's Patronus?", options: ["Cat", "Toad", "Snake", "Rat"], correctAnswer: 0 },
  { question: "Who replaced the Fat Lady after she was attacked?", options: ["The Grey Lady", "Sir Cadogan", "The Bloody Baron", "Violet"], correctAnswer: 1 },
  { question: "What is the max speed of a Firebolt?", options: ["100 mph", "120 mph", "150 mph", "200 mph"], correctAnswer: 2 },
  { question: "How many staircases does Hogwarts have?", options: ["142", "100", "99", "700"], correctAnswer: 0 },
  { question: "What is the number on the front of the Hogwarts Express?", options: ["5972", "4000", "9000", "1234"], correctAnswer: 0 },
  { question: "What dragon did Fleur face?", options: ["Common Welsh Green", "Swedish Short-Snout", "Chinese Fireball", "Hungarian Horntail"], correctAnswer: 0 },
  { question: "What dragon did Krum face?", options: ["Common Welsh Green", "Swedish Short-Snout", "Chinese Fireball", "Hungarian Horntail"], correctAnswer: 2 },
  { question: "What dragon did Cedric face?", options: ["Common Welsh Green", "Swedish Short-Snout", "Chinese Fireball", "Hungarian Horntail"], correctAnswer: 1 },
  { question: "Who is the caretaker of Hogwarts?", options: ["Hagrid", "Filch", "Flitwick", "Binns"], correctAnswer: 1 },
  { question: "Who is the librarian?", options: ["Madam Pomfrey", "Madam Pince", "Madam Hooch", "Professor Sprout"], correctAnswer: 1 },
  { question: "Who is the nurse?", options: ["Madam Pomfrey", "Madam Pince", "Madam Hooch", "Tonks"], correctAnswer: 0 },
  { question: "What separates the Forbidden Forest from the school grounds?", options: ["A wall", "A fence", "The Black Lake", "The Whomping Willow"], correctAnswer: 3 }, /* Technically grounds include forest, but distinct. Often Whomping Willow is near. Actually, just distance. Let's change question. */
  { question: "Who teaches Divination?", options: ["Professor Trelawney", "Professor Vector", "Professor Sinistra", "Professor Burbage"], correctAnswer: 0 },
  { question: "Who teaches Care of Magical Creatures (after Kettleburn)?", options: ["Hagrid", "Grubbly-Plank", "Lupin", "Sprout"], correctAnswer: 0 },
  { question: "What is the name of the centaur who teaches Divination?", options: ["Firenze", "Bane", "Ronan", "Magorian"], correctAnswer: 0 },
  { question: "What is the name of the Knight Bus conductor?", options: ["Stan Shunpike", "Ernie Prang", "Cornelius Fudge", "Tom"], correctAnswer: 0 },
  { question: "What is the name of the Knight Bus driver?", options: ["Stan Shunpike", "Ernie Prang", "Tom", "Leaky"], correctAnswer: 1 },
  { question: "Who is the Minister for Magic in Book 1?", options: ["Cornelius Fudge", "Rufus Scrimgeour", "Pius Thicknesse", "Kingsley Shacklebolt"], correctAnswer: 0 },
  { question: "Who succeeds Cornelius Fudge?", options: ["Rufus Scrimgeour", "Pius Thicknesse", "Kingsley Shacklebolt", "Arthur Weasley"], correctAnswer: 0 },
  { question: "Who kills Dobby?", options: ["Lucius Malfoy", "Bellatrix Lestrange", "Voldemort", "Fenrir Greyback"], correctAnswer: 1 },
  { question: "What is the last name of the three brothers in the Tale?", options: ["Peverell", "Potter", "Gaunt", "Black"], correctAnswer: 0 },
  { question: "What is Harry's middle name?", options: ["James", "Sirius", "Arthur", "Remus"], correctAnswer: 0 },
  { question: "What is Ron's middle name?", options: ["Bilius", "Arthur", "Septimus", "Hugo"], correctAnswer: 0 },
  { question: "What day is Harry's birthday?", options: ["July 30", "July 31", "August 1", "June 31"], correctAnswer: 1 },
  { question: "What day is Voldemort's birthday?", options: ["December 31", "October 31", "July 31", "January 1"], correctAnswer: 0 },
  { question: "What house was Tonks in?", options: ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"], correctAnswer: 1 },
  { question: "What house was Moaning Myrtle in?", options: ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"], correctAnswer: 2 },
  { question: "What house was Lockhart in?", options: ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"], correctAnswer: 2 },
  { question: "What house was Hagrid in?", options: ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"], correctAnswer: 0 },
  { question: "What house was Merlin in?", options: ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"], correctAnswer: 3 },
  { question: "What is the core of Draco Malfoy's wand?", options: ["Dragon Heartstring", "Unicorn Hair", "Phoenix Feather", "Veela Hair"], correctAnswer: 1 },
  { question: "What is the core of Hermione's wand?", options: ["Dragon Heartstring", "Unicorn Hair", "Phoenix Feather", "Veela Hair"], correctAnswer: 0 },
  { question: "What is the core of Ron's first wand?", options: ["Unicorn Hair", "Dragon Heartstring", "Phoenix Feather", "Ash"], correctAnswer: 0 }, /* Ash is wood */
  { question: "What wood is Ron's second wand?", options: ["Willow", "Ash", "Yew", "Vine"], correctAnswer: 0 },
  { question: "Who gave Harry the Gillyweed in the book?", options: ["Neville", "Dobby", "Ron", "Hermione"], correctAnswer: 1 },
  { question: "Who gave Harry the Gillyweed in the movie?", options: ["Neville", "Dobby", "Ron", "Hermione"], correctAnswer: 0 },
  { question: "How many points for catching the Snitch?", options: ["150", "100", "50", "200"], correctAnswer: 0 },
  { question: "What position does Harry play?", options: ["Chaser", "Keeper", "Seeker", "Beater"], correctAnswer: 2 },
  { question: "What position does Ron play?", options: ["Chaser", "Keeper", "Seeker", "Beater"], correctAnswer: 1 },
  { question: "What position did James Potter play?", options: ["Chaser", "Keeper", "Seeker", "Beater"], correctAnswer: 0 }, /* Movie says Seeker, Book implies Chaser mostly, but Rowling confirmed Chaser */
  { question: "Who is the captain of the Gryffindor team in Book 1?", options: ["Oliver Wood", "Angelina Johnson", "Harry Potter", "Charlie Weasley"], correctAnswer: 0 },
  { question: "Who is the captain of the Slytherin team in Book 2?", options: ["Marcus Flint", "Draco Malfoy", "Terence Higgs", "Blaise Zabini"], correctAnswer: 0 },
  { question: "What ball is used to score goals?", options: ["Quaffle", "Bludger", "Snitch", "Remembrall"], correctAnswer: 0 },
  { question: "What balls try to knock players off brooms?", options: ["Quaffles", "Bludgers", "Snitches", "Stones"], correctAnswer: 1 },
  { question: "How many players on a Quidditch team?", options: ["5", "6", "7", "8"], correctAnswer: 2 },
  { question: "Who wrote 'Fantastic Beasts and Where to Find Them'?", options: ["Newt Scamander", "Albus Dumbledore", "Bathilda Bagshot", "Harry Potter"], correctAnswer: 0 },
  { question: "Who wrote 'Quidditch Through the Ages'?", options: ["Kennilworthy Whisp", "Bathilda Bagshot", "Newt Scamander", "Gilderoy Lockhart"], correctAnswer: 0 },
  { question: "Who wrote 'The Tales of Beedle the Bard'?", options: ["Beedle the Bard", "Dumbledore", "Hermione", "Ron"], correctAnswer: 0 },
  { question: "Who teaches Muggle Studies?", options: ["Charity Burbage", "Alecto Carrow", "Bathsheda Babbling", "Septima Vector"], correctAnswer: 0 },
  { question: "Who kills Charity Burbage?", options: ["Voldemort", "Snape", "Bellatrix", "Draco"], correctAnswer: 0 },
  { question: "What is the name of the snake in the zoo (Book 1)?", options: ["Boa Constrictor", "Python", "Adder", "Cobra"], correctAnswer: 0 },
  { question: "Where was the snake in the zoo going?", options: ["Brazil", "Argentina", "Mexico", "Africa"], correctAnswer: 0 },
  { question: "What did Hagrid give Harry for his 11th birthday?", options: ["An Owl", "A Cake", "A Wand", "A Toad"], correctAnswer: 1 }, /* He brought the cake first, then bought the owl */
  { question: "What flavor bean did Dumbledore eat in the hospital wing?", options: ["Earwax", "Vomit", "Toffee", "Spinach"], correctAnswer: 0 },
  { question: "What flavor bean did George swear was a bogie?", options: ["Green", "Brown", "Yellow", "Red"], correctAnswer: 0 }, /* "You know how I think they have bogie flavored ones?" was Ron? No, George said "Watch out for the...". Actually Ron said "George swears he got a bogie flavored one once." */
  { question: "Who is the Gryffindor Head of House?", options: ["McGonagall", "Snape", "Flitwick", "Sprout"], correctAnswer: 0 },
  { question: "Who is the Slytherin Head of House?", options: ["Snape", "Slughorn", "McGonagall", "Flitwick"], correctAnswer: 0 },
  { question: "Who is the Ravenclaw Head of House?", options: ["Flitwick", "Sprout", "McGonagall", "Snape"], correctAnswer: 0 },
  { question: "Who is the Hufflepuff Head of House?", options: ["Sprout", "Flitwick", "McGonagall", "Snape"], correctAnswer: 0 },
  { question: "What year did Harry and Ginny get married?", options: ["Unknown in books", "2000", "1999", "2002"], correctAnswer: 0 }, /* Trick question maybe? */
  { question: "What is the final chapter of Book 7 called?", options: ["The Flaw in the Plan", "19 Years Later", "The Forest Again", "King's Cross"], correctAnswer: 1 },
  { question: "Who said 'Not my daughter, you bitch!'?", options: ["Molly Weasley", "Lily Potter", "McGonagall", "Ginny Weasley"], correctAnswer: 0 },
  { question: "Who marked Harry as his equal?", options: ["Voldemort", "Dumbledore", "Snape", "Trelawney"], correctAnswer: 0 },
  { question: "Who was the Secret Keeper for the Potters?", options: ["Peter Pettigrew", "Sirius Black", "Remus Lupin", "Dumbledore"], correctAnswer: 0 },
  { question: "Who did the Potters pretend was their Secret Keeper?", options: ["Sirius Black", "Remus Lupin", "Peter Pettigrew", "James Potter"], correctAnswer: 0 },
  { question: "What is the name of Lupin's wife?", options: ["Nymphadora Tonks", "Lily Potter", "Molly Weasley", "Fleur Delacour"], correctAnswer: 0 },
  { question: "Who is Bill Weasley's wife?", options: ["Fleur Delacour", "Tonks", "Hermione", "Angelina"], correctAnswer: 0 },
  { question: "Who is Percy Weasley's wife?", options: ["Audrey", "Penelope", "Padma", "Pansy"], correctAnswer: 0 },
  { question: "Who is George Weasley's wife?", options: ["Angelina Johnson", "Alicia Spinnet", "Katie Bell", "Luna Lovegood"], correctAnswer: 0 },
  { question: "Who is Draco Malfoy's wife?", options: ["Astoria Greengrass", "Pansy Parkinson", "Daphne Greengrass", "Millicent Bulstrode"], correctAnswer: 0 },
  { question: "What is Neville's wife's name?", options: ["Hannah Abbott", "Luna Lovegood", "Ginny Weasley", "Susan Bones"], correctAnswer: 0 },
  { question: "What profession does Harry choose?", options: ["Auror", "Professor", "Minister", "Quidditch Player"], correctAnswer: 0 },
  { question: "What profession does Ginny choose?", options: ["Quidditch Player", "Auror", "Healer", "Writer"], correctAnswer: 0 },
  { question: "What profession does Neville choose?", options: ["Herbology Professor", "Auror", "Healer", "Ministry Official"], correctAnswer: 0 },
  { question: "What profession does Hermione choose?", options: ["Minister for Magic", "Professor", "Lawyer", "Auror"], correctAnswer: 0 },
  { question: "Who is the master of death?", options: ["One who unites the Hallows", "Voldemort", "Dumbledore", "Snape"], correctAnswer: 0 },
  { question: "What is the motto of Hogwarts?", options: ["Draco Dormiens Nunquam Titillandus", "Carpe Diem", "Semper Fidelis", "E Pluribus Unum"], correctAnswer: 0 },
  { question: "What does the Hogwarts motto translate to?", options: ["Never tickle a sleeping dragon", "Seize the day", "Always faithful", "Out of many, one"], correctAnswer: 0 },
  { question: "Where is the kitchen in Hogwarts?", options: ["Behind a painting of a fruit bowl", "In the basement", "Next to the Great Hall", "In the dungeons"], correctAnswer: 0 },
  { question: "What must you tickle to enter the kitchen?", options: ["A pear", "A banana", "A grape", "An apple"], correctAnswer: 0 },
  { question: "Who found the Room of Requirement first (in the timeline)?", options: ["Tom Riddle", "Harry Potter", "Dumbledore", "Neville"], correctAnswer: 0 }, /* Likely Tom Riddle or Dumbledore by accident */
  { question: "What did Dumbledore see in the Mirror of Erised?", options: ["His family alive and whole", "Socks", "Himself as Minister", "Fawkes"], correctAnswer: 1 }, /* He told Harry socks. Truly? Family. */
  { question: "What is the name of the female elf Winky belonged to?", options: ["Barty Crouch Sr.", "Hepzibah Smith", "Regulus Black", "Lucius Malfoy"], correctAnswer: 0 },
  { question: "Who owned Hokey?", options: ["Hepzibah Smith", "Barty Crouch", "Tom Riddle", "Slughorn"], correctAnswer: 0 },
  { question: "Who owned Kreacher?", options: ["Sirius Black", "Regulus Black", "Walburga Black", "All of them"], correctAnswer: 3 },
  { question: "Who killed Dumbledore's sister Ariana?", options: ["Unknown/Accidental", "Grindelwald", "Albus", "Aberforth"], correctAnswer: 0 },
  { question: "What is the name of Dumbledore's sister?", options: ["Ariana", "Kendra", "Honoria", "Bathilda"], correctAnswer: 0 },
  { question: "What is the name of Dumbledore's mother?", options: ["Kendra", "Ariana", "Honoria", "Bathilda"], correctAnswer: 0 },
  { question: "What is the name of Dumbledore's father?", options: ["Percival", "Wulfric", "Brian", "Aberforth"], correctAnswer: 0 },
  { question: "What village did the Dumbledores live in?", options: ["Mould-on-the-Wold", "Godric's Hollow", "Hogsmeade", "Little Hangleton"], correctAnswer: 0 }, /* Before Godric's Hollow */
  { question: "Where did they move to after the father was imprisoned?", options: ["Godric's Hollow", "Mould-on-the-Wold", "Hogsmeade", "Ottery St Catchpole"], correctAnswer: 0 },
  { question: "Who wrote the Daily Prophet article about Dumbledore?", options: ["Rita Skeeter", "Elphias Doge", "Bathilda Bagshot", "Luna Lovegood"], correctAnswer: 0 },
  { question: "Who wrote the obituary for Dumbledore?", options: ["Elphias Doge", "Rita Skeeter", "Harry Potter", "McGonagall"], correctAnswer: 0 },
  { question: "What is the name of Rita Skeeter's book about Dumbledore?", options: ["The Life and Lies of Albus Dumbledore", "The Truth About Albus", "Dumbledore's Secrets", "Albus Dumbledore: A History"], correctAnswer: 0 },
  { question: "What form is Rita Skeeter's animagus?", options: ["Beetle", "Fly", "Spider", "Wasp"], correctAnswer: 0 },
  { question: "Is Rita Skeeter a registered animagus?", options: ["No", "Yes", "Only in America", "Yes, as a journalist"], correctAnswer: 0 },
  { question: "Who blackmailed Rita Skeeter?", options: ["Hermione", "Harry", "Dumbledore", "Snape"], correctAnswer: 0 },
  { question: "What did Hermione keep Rita in?", options: ["A jar", "A box", "A cage", "A bottle"], correctAnswer: 0 },
  { question: "Who gave Harry the pocket sneakoscope?", options: ["Ron", "Hermione", "Sirius", "Hagrid"], correctAnswer: 0 },
  { question: "Who is the host of 'Potterwatch'?", options: ["Lee Jordan", "Fred Weasley", "George Weasley", "Remus Lupin"], correctAnswer: 0 },
  { question: "What was Lee Jordan's code name on Potterwatch?", options: ["River", "Rapier", "Royal", "Romulus"], correctAnswer: 0 },
  { question: "What was Kingsley's code name on Potterwatch?", options: ["Royal", "River", "Rapier", "Romulus"], correctAnswer: 0 },
  { question: "What was Lupin's code name on Potterwatch?", options: ["Romulus", "Remus", "Rapier", "River"], correctAnswer: 0 },
  { question: "What was Fred's code name on Potterwatch?", options: ["Rapier", "Rodent", "River", "Royal"], correctAnswer: 0 }, /* Or maybe George. One of them. */
  { question: "What is the password to Potterwatch?", options: ["Varies", "Albus", "Harry", "Phoenix"], correctAnswer: 0 },
  { question: "Who destroyed the Diadem?", options: ["Crabbe (Fiendfyre)", "Harry (Basilisk Fang)", "Ron (Sword)", "Hermione (Fang)"], correctAnswer: 0 },
  { question: "Who died in the Room of Requirement fire?", options: ["Vincent Crabbe", "Gregory Goyle", "Draco Malfoy", "Blaise Zabini"], correctAnswer: 0 },
  { question: "Which ear did George lose?", options: ["Left", "Right", "Both", "None"], correctAnswer: 0 },
  { question: "Who cut off George's ear?", options: ["Snape", "Bellatrix", "Dolohov", "Voldemort"], correctAnswer: 0 },
  { question: "What spell cut off George's ear?", options: ["Sectumsempra", "Avada Kedavra", "Diffindo", "Confringo"], correctAnswer: 0 },
  { question: "What was the first password to Gryffindor Tower in Book 1?", options: ["Caput Draconis", "Pig Snout", "Wattlebird", "Fortuna Major"], correctAnswer: 0 },
  { question: "Who guarded the Gryffindor common room when the Fat Lady fled?", options: ["Sir Cadogan", "The Bloody Baron", "The Grey Lady", "The Fat Friar"], correctAnswer: 0 },
  { question: "What was the password Sir Cadogan changed constantly?", options: ["Many passwords", "Scurvy Cur", "Oddsbodikins", "All of the above"], correctAnswer: 3 },
  { question: "Who attacked the Fat Lady?", options: ["Sirius Black", "Peeves", "Peter Pettigrew", "Voldemort"], correctAnswer: 0 },
  { question: "How did Sirius enter the castle?", options: ["Through a secret tunnel", "Through the front door", "Flew in", "Apparated"], correctAnswer: 0 }, /* Also had passwords from Crookshanks */
  { question: "Who provided the passwords to Sirius?", options: ["Crookshanks", "Neville", "Harry", "Lupin"], correctAnswer: 0 },
  { question: "Whose password list did Crookshanks steal?", options: ["Neville's", "Harry's", "Ron's", "Seamus's"], correctAnswer: 0 },
  { question: "What breed is Fang?", options: ["Boarhound", "Great Dane", "Mastiff", "Bulldog"], correctAnswer: 0 },
  { question: "What kind of dragon is Norberta?", options: ["Norwegian Ridgeback", "Hungarian Horntail", "Chinese Fireball", "Common Welsh Green"], correctAnswer: 0 },
  { question: "Who took Norbert to Romania?", options: ["Charlie's friends", "Charlie", "Hagrid", "Dumbledore"], correctAnswer: 0 },
  { question: "What is the name of the vampire Slughorn introduces?", options: ["Sanguini", "Dracula", "Nosferatu", "Vlad"], correctAnswer: 0 },
  { question: "Who wrote the foreword to Quidditch Through the Ages?", options: ["Dumbledore", "Harry Potter", "Kennilworthy Whisp", "Bagshot"], correctAnswer: 0 },
  { question: "What team does Ron support?", options: ["Chudley Cannons", "Puddlemere United", "Holyhead Harpies", "Falmouth Falcons"], correctAnswer: 0 },
  { question: "What team does Cho Chang support?", options: ["Tutshill Tornados", "Chudley Cannons", "Puddlemere United", "Kenmare Kestrels"], correctAnswer: 0 },
  { question: "What team did Ginny play for professionally?", options: ["Holyhead Harpies", "Chudley Cannons", "Puddlemere United", "Gwenog Jones"], correctAnswer: 0 },
  { question: "Who is the Captain of the Holyhead Harpies?", options: ["Gwenog Jones", "Angelina Johnson", "Ginny Weasley", "Alicia Spinnet"], correctAnswer: 0 },
  { question: "What is the name of the orphanage Voldemort grew up in?", options: ["Wool's Orphanage", "St. Jerome's", "Little Hangleton", "The Gaunt Shack"], correctAnswer: 0 },
  { question: "What did Dumbledore set on fire in the orphanage?", options: ["A wardrobe", "A bed", "A toy", "Tom's hair"], correctAnswer: 0 },
  { question: "What did Tom Riddle steal from other children?", options: ["Harmonica, Yo-yo, Thimble", "Wand, Book, Ball", "Money, Candy, Clothes", "Nothing"], correctAnswer: 0 },
  { question: "Where did Tom Riddle take the children to torture them?", options: ["A cave", "The basement", "The roof", "The forest"], correctAnswer: 0 },
  { question: "Who did Tom Riddle frame for the Chamber of Secrets attacks?", options: ["Hagrid", "Dumbledore", "Slughorn", "Dippet"], correctAnswer: 0 },
  { question: "Who was Headmaster when Tom Riddle was at school?", options: ["Armando Dippet", "Albus Dumbledore", "Phineas Nigellus", "Dilys Derwent"], correctAnswer: 0 },
  { question: "What subject did Tom Riddle want to teach?", options: ["Defence Against the Dark Arts", "Potions", "Transfiguration", "History of Magic"], correctAnswer: 0 },
  { question: "Where did Voldemort work after leaving Hogwarts?", options: ["Borgin and Burkes", "Ministry of Magic", "Hogwarts", "Gringotts"], correctAnswer: 0 },
  { question: "Who did Voldemort kill to make the Locket Horcrux?", options: ["A muggle tramp", "Hepzibah Smith", "His father", "Bertha Jorkins"], correctAnswer: 0 },
  { question: "Who did Voldemort kill to make the Cup Horcrux?", options: ["Hepzibah Smith", "A muggle tramp", "His grandparents", "Frank Bryce"], correctAnswer: 0 },
  { question: "Who did Voldemort kill to make the Diadem Horcrux?", options: ["An Albanian peasant", "The Grey Lady", "A student", "Tom Riddle Sr."], correctAnswer: 0 },
  { question: "Who did Voldemort kill to make the Diary Horcrux?", options: ["Moaning Myrtle", "Tom Riddle Sr.", "Hepzibah Smith", "Frank Bryce"], correctAnswer: 0 },
  { question: "Who did Voldemort kill to make the Ring Horcrux?", options: ["Tom Riddle Sr.", "Moaning Myrtle", "Hepzibah Smith", "Frank Bryce"], correctAnswer: 0 },
  { question: "Who did Voldemort kill to make the Nagini Horcrux?", options: ["Bertha Jorkins", "Frank Bryce", "Charity Burbage", "Cedric Diggory"], correctAnswer: 0 },
  { question: "Who did Voldemort kill to make the Harry Horcrux?", options: ["Lily Potter (Unintentional)", "James Potter", "Himself", "Snape"], correctAnswer: 0 },
];

export const OPPONENT_NAMES = [
  "Lord Voldemort",
  "Bellatrix Lestrange",
  "Severus Snape",
  "Draco Malfoy",
  "Lucius Malfoy",
  "Fenrir Greyback",
  "Dolores Umbridge",
  "Peter Pettigrew",
  "Barty Crouch Jr."
];

export const WAND_WOODS: WandWood[] = [
  { id: 'holly', name: 'Holly', description: 'A rare kind of wood, traditionally considered protective.', cost: 500, attackBonus: 30, color: '#e2d7c0' },
  { id: 'yew', name: 'Yew', description: 'Sap is poisonous. Often associated with dark wizards.', cost: 800, attackBonus: 60, color: '#d9a67a' },
  { id: 'ash', name: 'Ash', description: 'Stubborn wood. Cleaves to its one true master.', cost: 600, attackBonus: 40, color: '#c7b299' },
  { id: 'vine', name: 'Vine', description: 'For those who seek a higher purpose.', cost: 700, attackBonus: 45, color: '#8b5a2b' },
  { id: 'elder', name: 'Elder', description: 'The rarest wand wood of all. Very unlucky.', cost: 2000, attackBonus: 100, color: '#5c4033' },
  { id: 'cherry', name: 'Cherry', description: 'Prized in Mahoutokoro. Makes lethal wands.', cost: 900, attackBonus: 70, color: '#a0522d' },
  { id: 'hawthorn', name: 'Hawthorn', description: 'A complex, intriguing wood.', cost: 750, attackBonus: 50, color: '#6d4c41' },
  { id: 'walnut', name: 'Walnut', description: 'For highly intelligent witches and wizards.', cost: 650, attackBonus: 45, color: '#4e342e' },
];

export const WAND_CORES: WandCore[] = [
  { id: 'unicorn', name: 'Unicorn Hair', description: 'Produces the most consistent magic. Hard to turn to the Dark Arts.', cost: 400, defenseBonus: 50, image: '🦄' },
  { id: 'dragon', name: 'Dragon Heartstring', description: 'Produces the most power. Capable of flamboyant spells.', cost: 600, defenseBonus: 20, image: '🐉' },
  { id: 'phoenix', name: 'Phoenix Feather', description: 'Capable of the greatest range of magic. Hard to tame.', cost: 800, defenseBonus: 40, image: '🔥' },
  { id: 'thestral', name: 'Thestral Hair', description: 'Unstable and tricky, but potent.', cost: 1200, defenseBonus: 10, image: '💀' },
  { id: 'veela', name: 'Veela Hair', description: 'Temperamental. Good for charms.', cost: 500, defenseBonus: 30, image: '🧚‍♀️' },
];

export const WAND_COLORS: WandColor[] = [
  { id: 'natural', name: 'Natural Polish', hex: 'transparent', cost: 0 },
  { id: 'midnight', name: 'Midnight Blue', hex: '#1e3a8a', cost: 100 },
  { id: 'blood', name: 'Blood Red', hex: '#7f1d1d', cost: 100 },
  { id: 'emerald', name: 'Emerald Green', hex: '#064e3b', cost: 100 },
  { id: 'void', name: 'Void Black', hex: '#0f172a', cost: 200 },
  { id: 'ivory', name: 'Ivory White', hex: '#f8fafc', cost: 150 },
  { id: 'gold', name: 'Gilded', hex: '#ca8a04', cost: 500 },
];

export const SHOP_ITEMS: GameItem[] = [
  // WANDS
  { id: 2001, name: "10\" Oak, Dragon Heartstring", description: "Reliable and sturdy. Good for transfiguration.", price: 500, type: 'wand', attack: 45, defense: 10, imageUrl: "https://picsum.photos/seed/wand_oak/200/200" },
  { id: 2002, name: "11\" Holly, Phoenix Feather", description: "A brother to the Dark Lord's wand.", price: 3000, type: 'wand', attack: 280, defense: 50, imageUrl: "https://picsum.photos/seed/wand_harry/200/200" },
  { id: 2003, name: "14\" Willow, Unicorn Hair", description: "Great for charms work. belonged to a famous redhead.", price: 450, type: 'wand', attack: 40, defense: 15, imageUrl: "https://picsum.photos/seed/wand_willow/200/200" },
  { id: 2004, name: "12\" Ash, Unicorn Hair", description: "Stubborn wand for a stubborn wizard.", price: 400, type: 'wand', attack: 35, defense: 10, imageUrl: "https://picsum.photos/seed/wand_ash/200/200" },
  { id: 2005, name: "13.5\" Yew, Dragon Heartstring", description: "Powerful and precise. Often associated with dueling.", price: 1200, type: 'wand', attack: 110, defense: 20, imageUrl: "https://picsum.photos/seed/wand_yew/200/200" },
  { id: 2006, name: "15\" Elder, Thestral Hair", description: "The Deathstick. Unbeatable.", price: 50000, type: 'wand', attack: 500, defense: 100, imageUrl: "https://picsum.photos/seed/wand_elder/200/200" },
  { id: 2007, name: "10.75\" Vine, Dragon Heartstring", description: "Sensitive and intelligent.", price: 800, type: 'wand', attack: 75, defense: 30, imageUrl: "https://picsum.photos/seed/wand_vine/200/200" },
  { id: 2008, name: "10.25\" Cypress, Unicorn Hair", description: "Associated with nobility. Ideal for self-sacrifice.", price: 700, type: 'wand', attack: 65, defense: 25, imageUrl: "https://picsum.photos/seed/wand_cypress/200/200" },
  { id: 2009, name: "9.5\" Fir, Dragon Heartstring", description: "Resilient. Requires strength of mind.", price: 650, type: 'wand', attack: 60, defense: 20, imageUrl: "https://picsum.photos/seed/wand_fir/200/200" },
  { id: 2010, name: "13\" Cherry, Unicorn Hair", description: "Prized in Japan. Possesses lethal power.", price: 900, type: 'wand', attack: 85, defense: 15, imageUrl: "https://picsum.photos/seed/wand_cherry/200/200" },
  { id: 2011, name: "18\" Elm, Dragon Heartstring", description: "Dignified. Produces the fewest accidents.", price: 1100, type: 'wand', attack: 95, defense: 35, imageUrl: "https://picsum.photos/seed/wand_elm/200/200" },
  { id: 2012, name: "12.75\" Walnut, Dragon Heartstring", description: "For the highly intelligent witch or wizard.", price: 1000, type: 'wand', attack: 90, defense: 10, imageUrl: "https://picsum.photos/seed/wand_walnut/200/200" },
  { id: 2013, name: "10\" Hawthorn, Unicorn Hair", description: "Complex and intriguing. Good for healing and curses.", price: 850, type: 'wand', attack: 70, defense: 40, imageUrl: "https://picsum.photos/seed/wand_hawthorn/200/200" },
  { id: 2014, name: "9.5\" Rosewood, Veela Hair", description: "Beautiful and temperamental.", price: 1500, type: 'wand', attack: 100, defense: 60, imageUrl: "https://picsum.photos/seed/wand_rosewood/200/200" },
  { id: 2015, name: "11\" Blackthorn, Dragon Heartstring", description: "Best suited for a warrior.", price: 950, type: 'wand', attack: 92, defense: 25, imageUrl: "https://picsum.photos/seed/wand_blackthorn/200/200" },
  { id: 2016, name: "10.25\" Hornbeam, Dragon Heartstring", description: "For one with a singular passion.", price: 880, type: 'wand', attack: 82, defense: 18, imageUrl: "https://picsum.photos/seed/wand_hornbeam/200/200" },
  { id: 2017, name: "9.25\" Chestnut, Dragon Heartstring", description: "Attracted to skilled tamers of beasts.", price: 720, type: 'wand', attack: 68, defense: 22, imageUrl: "https://picsum.photos/seed/wand_chestnut/200/200" },
  { id: 2018, name: "11.5\" Aspen, Phoenix Feather", description: "Outstanding for martial magic. The duelist's wand.", price: 1300, type: 'wand', attack: 115, defense: 45, imageUrl: "https://picsum.photos/seed/wand_aspen/200/200" },
  { id: 2019, name: "10.5\" Cedar, Dragon Heartstring", description: "For the perspicacious and loyal.", price: 780, type: 'wand', attack: 72, defense: 28, imageUrl: "https://picsum.photos/seed/wand_cedar/200/200" },
  { id: 2020, name: "11\" Dogwood, Unicorn Hair", description: "Playful and mischievous. Refuses non-verbal spells.", price: 620, type: 'wand', attack: 55, defense: 12, imageUrl: "https://picsum.photos/seed/wand_dogwood/200/200" },
  { id: 2021, name: "13.25\" Ebony, Dragon Heartstring", description: "For those who hold fast to their beliefs.", price: 1400, type: 'wand', attack: 120, defense: 30, imageUrl: "https://picsum.photos/seed/wand_ebony/200/200" },
  { id: 2022, name: "9.75\" Hazel, Unicorn Hair", description: "Sensitive. Reflects its owner's emotional state.", price: 680, type: 'wand', attack: 62, defense: 35, imageUrl: "https://picsum.photos/seed/wand_hazel/200/200" },
  { id: 2023, name: "12\" Larch, Phoenix Feather", description: "Instills courage and confidence.", price: 920, type: 'wand', attack: 88, defense: 32, imageUrl: "https://picsum.photos/seed/wand_larch/200/200" },
  { id: 2024, name: "11.25\" Laurel, Dragon Heartstring", description: "Cannot perform a dishonorable act.", price: 860, type: 'wand', attack: 80, defense: 50, imageUrl: "https://picsum.photos/seed/wand_laurel/200/200" },
  { id: 2025, name: "10\" Maple, Phoenix Feather", description: "For the traveller and explorer.", price: 890, type: 'wand', attack: 84, defense: 26, imageUrl: "https://picsum.photos/seed/wand_maple/200/200" },
  { id: 2026, name: "12.5\" Pear, Unicorn Hair", description: "Resilient. Never looks worn.", price: 710, type: 'wand', attack: 66, defense: 38, imageUrl: "https://picsum.photos/seed/wand_pear/200/200" },
  { id: 2027, name: "11\" Pine, Phoenix Feather", description: "For the independent and individual.", price: 940, type: 'wand', attack: 89, defense: 29, imageUrl: "https://picsum.photos/seed/wand_pine/200/200" },
  { id: 2028, name: "10.75\" Poplar, Dragon Heartstring", description: "A wand you can rely upon. Consistent.", price: 640, type: 'wand', attack: 58, defense: 42, imageUrl: "https://picsum.photos/seed/wand_poplar/200/200" },
  { id: 2029, name: "10\" Red Oak, Unicorn Hair", description: "Fast reactions. Perfect for dueling.", price: 980, type: 'wand', attack: 94, defense: 15, imageUrl: "https://picsum.photos/seed/wand_redoak/200/200" },
  { id: 2030, name: "11.5\" Redwood, Phoenix Feather", description: "Bring good fortune to its owner.", price: 1600, type: 'wand', attack: 105, defense: 55, imageUrl: "https://picsum.photos/seed/wand_redwood/200/200" },
  { id: 2031, name: "12.25\" Rowan, Unicorn Hair", description: "Produces the strongest defensive charms.", price: 850, type: 'wand', attack: 40, defense: 90, imageUrl: "https://picsum.photos/seed/wand_rowan/200/200" },
  { id: 2032, name: "10.5\" Silver Lime, Dragon Heartstring", description: "Rare. Favored by Seers and Legilimens.", price: 1150, type: 'wand', attack: 98, defense: 48, imageUrl: "https://picsum.photos/seed/wand_silverlime/200/200" },
  { id: 2033, name: "9\" Spruce, Unicorn Hair", description: "Requires a firm hand. Not for the tentative.", price: 730, type: 'wand', attack: 69, defense: 21, imageUrl: "https://picsum.photos/seed/wand_spruce/200/200" },
  { id: 2034, name: "11\" Sycamore, Dragon Heartstring", description: "Craves variety. Combusts if bored.", price: 760, type: 'wand', attack: 74, defense: 14, imageUrl: "https://picsum.photos/seed/wand_sycamore/200/200" },
  
  // SPELLS
  { id: 3001, name: "Expelliarmus", description: "The Disarming Charm. A dueling staple.", price: 200, type: 'spell', attack: 20, defense: 10, imageUrl: "https://picsum.photos/seed/spell_expelliarmus/200/200" },
  { id: 3002, name: "Stupefy", description: "Stuns the target, rendering them unconscious.", price: 300, type: 'spell', attack: 35, defense: 5, imageUrl: "https://picsum.photos/seed/spell_stupefy/200/200" },
  { id: 3003, name: "Protego", description: "The Shield Charm. Reflects minor spells.", price: 250, type: 'spell', attack: 0, defense: 40, imageUrl: "https://picsum.photos/seed/spell_protego/200/200" },
  { id: 3004, name: "Incendio", description: "Conjures a jet of flames.", price: 350, type: 'spell', attack: 45, defense: 0, imageUrl: "https://picsum.photos/seed/spell_incendio/200/200" },
  { id: 3005, name: "Petrificus Totalus", description: "Full Body-Bind Curse.", price: 400, type: 'spell', attack: 30, defense: 20, imageUrl: "https://picsum.photos/seed/spell_petrificus/200/200" },
  { id: 3006, name: "Flipendo", description: "Knockback Jinx. Pushes enemies away.", price: 150, type: 'spell', attack: 15, defense: 10, imageUrl: "https://picsum.photos/seed/spell_flipendo/200/200" },
  { id: 3007, name: "Rictusempra", description: "Tickling Charm. Distracts the opponent.", price: 180, type: 'spell', attack: 10, defense: 15, imageUrl: "https://picsum.photos/seed/spell_rictusempra/200/200" },
  { id: 3008, name: "Wingardium Leviosa", description: "Levitation Charm. Drop things on foes.", price: 100, type: 'spell', attack: 10, defense: 5, imageUrl: "https://picsum.photos/seed/spell_wingardium/200/200" },
  { id: 3009, name: "Lumos Solem", description: "Blinding flash of sunlight.", price: 220, type: 'spell', attack: 15, defense: 25, imageUrl: "https://picsum.photos/seed/spell_lumos/200/200" },
  { id: 3010, name: "Confringo", description: "Blasting Curse. Causes an explosion.", price: 600, type: 'spell', attack: 70, defense: 0, imageUrl: "https://picsum.photos/seed/spell_confringo/200/200" },
  { id: 3011, name: "Diffindo", description: "Severing Charm. Cuts through defenses.", price: 450, type: 'spell', attack: 55, defense: 0, imageUrl: "https://picsum.photos/seed/spell_diffindo/200/200" },
  { id: 3012, name: "Bombarda", description: "Provokes a small explosion.", price: 500, type: 'spell', attack: 60, defense: 0, imageUrl: "https://picsum.photos/seed/spell_bombarda/200/200" },
  { id: 3013, name: "Bombarda Maxima", description: "Provokes a large explosion.", price: 800, type: 'spell', attack: 90, defense: 0, imageUrl: "https://picsum.photos/seed/spell_bombardamax/200/200" },
  { id: 3014, name: "Reducto", description: "Reductor Curse. Blasts solid objects to dust.", price: 550, type: 'spell', attack: 65, defense: 0, imageUrl: "https://picsum.photos/seed/spell_reducto/200/200" },
  { id: 3015, name: "Sectumsempra", description: "For enemies. Causes deep cuts.", price: 2000, type: 'spell', attack: 150, defense: 0, imageUrl: "https://picsum.photos/seed/spell_sectumsempra/200/200" },
  { id: 3016, name: "Levicorpus", description: "Dangles the victim by their ankle.", price: 300, type: 'spell', attack: 25, defense: 25, imageUrl: "https://picsum.photos/seed/spell_levicorpus/200/200" },
  { id: 3017, name: "Oppugno", description: "Directs objects to attack.", price: 350, type: 'spell', attack: 35, defense: 10, imageUrl: "https://picsum.photos/seed/spell_oppugno/200/200" },
  { id: 3018, name: "Serpensortia", description: "Summons a snake.", price: 400, type: 'spell', attack: 40, defense: 10, imageUrl: "https://picsum.photos/seed/spell_serpensortia/200/200" },
  { id: 3019, name: "Aguamenti", description: "Conjures water. Extinguishes fires.", price: 150, type: 'spell', attack: 5, defense: 30, imageUrl: "https://picsum.photos/seed/spell_aguamenti/200/200" },
  { id: 3020, name: "Glacius", description: "Freezes the target.", price: 380, type: 'spell', attack: 30, defense: 30, imageUrl: "https://picsum.photos/seed/spell_glacius/200/200" },
  { id: 3021, name: "Episkey", description: "Heals minor injuries instantly.", price: 500, type: 'spell', attack: 0, defense: 60, imageUrl: "https://picsum.photos/seed/spell_episkey/200/200" },
  { id: 3022, name: "Protego Totalum", description: "Protects an area from spells.", price: 700, type: 'spell', attack: 0, defense: 80, imageUrl: "https://picsum.photos/seed/spell_prototal/200/200" },
  { id: 3023, name: "Salvio Hexia", description: "Deflects hexes.", price: 650, type: 'spell', attack: 0, defense: 70, imageUrl: "https://picsum.photos/seed/spell_salvio/200/200" },
  { id: 3024, name: "Expecto Patronum", description: "Summons a spirit guardian.", price: 1200, type: 'spell', attack: 20, defense: 120, imageUrl: "https://picsum.photos/seed/spell_patronus/200/200" },
  { id: 3025, name: "Riddikulus", description: "Forces a boggart to assume a funny shape.", price: 250, type: 'spell', attack: 15, defense: 20, imageUrl: "https://picsum.photos/seed/spell_riddikulus/200/200" },
  { id: 3026, name: "Confundo", description: "Causes confusion.", price: 450, type: 'spell', attack: 20, defense: 40, imageUrl: "https://picsum.photos/seed/spell_confundo/200/200" },
  { id: 3027, name: "Obliviate", description: "Erases memories. Disorienting.", price: 800, type: 'spell', attack: 10, defense: 80, imageUrl: "https://picsum.photos/seed/spell_obliviate/200/200" },
  { id: 3028, name: "Langlock", description: "Glues the victim's tongue to the roof of their mouth.", price: 320, type: 'spell', attack: 25, defense: 15, imageUrl: "https://picsum.photos/seed/spell_langlock/200/200" },
  { id: 3029, name: "Furnunculus", description: "Covers the target in boils.", price: 280, type: 'spell', attack: 30, defense: 5, imageUrl: "https://picsum.photos/seed/spell_furnunculus/200/200" },
  { id: 3030, name: "Tarantallegra", description: "Forces the legs to dance uncontrollably.", price: 330, type: 'spell', attack: 28, defense: 10, imageUrl: "https://picsum.photos/seed/spell_tarantallegra/200/200" },
  { id: 3031, name: "Silencio", description: "Silences the target.", price: 420, type: 'spell', attack: 10, defense: 40, imageUrl: "https://picsum.photos/seed/spell_silencio/200/200" },
  { id: 3032, name: "Incarcerous", description: "Binds the target with ropes.", price: 480, type: 'spell', attack: 20, defense: 45, imageUrl: "https://picsum.photos/seed/spell_incarcerous/200/200" },
  { id: 3033, name: "Locomotor Mortis", description: "Leg-Locker Curse.", price: 290, type: 'spell', attack: 25, defense: 10, imageUrl: "https://picsum.photos/seed/spell_locomotor/200/200" },
  { id: 3034, name: "Fiendfyre", description: "Cursed fire that incinerates everything.", price: 5000, type: 'spell', attack: 300, defense: 0, imageUrl: "https://picsum.photos/seed/spell_fiendfyre/200/200" },
  
  // EQUIPMENT
  { id: 4001, name: "Hogwarts School Robes", description: "Standard uniform. Plain black.", price: 50, type: 'equipment', attack: 0, defense: 10, imageUrl: "https://picsum.photos/seed/equip_robes/200/200" },
  { id: 4002, name: "Winter Cloak", description: "Heavy wool with silver fastenings.", price: 120, type: 'equipment', attack: 0, defense: 25, imageUrl: "https://picsum.photos/seed/equip_cloak/200/200" },
  { id: 4003, name: "Dragon-Hide Gloves", description: "Essential for handling dangerous plants.", price: 200, type: 'equipment', attack: 5, defense: 30, imageUrl: "https://picsum.photos/seed/equip_gloves/200/200" },
  { id: 4004, name: "Pointed Hat", description: "For day wear. Stiffened.", price: 40, type: 'equipment', attack: 0, defense: 5, imageUrl: "https://picsum.photos/seed/equip_hat/200/200" },
  { id: 4005, name: "Protective Goggles", description: "For Quidditch or Potions.", price: 80, type: 'equipment', attack: 0, defense: 15, imageUrl: "https://picsum.photos/seed/equip_goggles/200/200" },
  { id: 4006, name: "Quidditch Helmet", description: "Leather, padded.", price: 150, type: 'equipment', attack: 0, defense: 20, imageUrl: "https://picsum.photos/seed/equip_helmet/200/200" },
  { id: 4007, name: "Quidditch Pads", description: "Elbow and knee protection.", price: 100, type: 'equipment', attack: 0, defense: 15, imageUrl: "https://picsum.photos/seed/equip_pads/200/200" },
  { id: 4008, name: "Nimbus 2000", description: "Fast, maneuverable broomstick.", price: 2000, type: 'equipment', attack: 50, defense: 50, imageUrl: "https://picsum.photos/seed/equip_nimbus2000/200/200" },
  { id: 4009, name: "Nimbus 2001", description: "Faster than the 2000. Sleek black.", price: 2500, type: 'equipment', attack: 60, defense: 55, imageUrl: "https://picsum.photos/seed/equip_nimbus2001/200/200" },
  { id: 4010, name: "Firebolt", description: "The fastest broom in the world.", price: 5000, type: 'equipment', attack: 100, defense: 80, imageUrl: "https://picsum.photos/seed/equip_firebolt/200/200" },
  { id: 4011, name: "Cleansweep Seven", description: "Reliable, if not flashy.", price: 800, type: 'equipment', attack: 30, defense: 30, imageUrl: "https://picsum.photos/seed/equip_cleansweep/200/200" },
  { id: 4012, name: "Comet 260", description: "Good braking charm. A bit slow.", price: 600, type: 'equipment', attack: 20, defense: 25, imageUrl: "https://picsum.photos/seed/equip_comet/200/200" },
  { id: 4013, name: "Remembrall", description: "Turns red if you've forgotten something.", price: 50, type: 'equipment', attack: 0, defense: 5, imageUrl: "https://picsum.photos/seed/equip_remembrall/200/200" },
  { id: 4014, name: "Sneakoscope", description: "Lights up when someone untrustworthy is near.", price: 150, type: 'equipment', attack: 0, defense: 20, imageUrl: "https://picsum.photos/seed/equip_sneakoscope/200/200" },
  { id: 4015, name: "Omnioculars", description: "Replay action, slow motion.", price: 300, type: 'equipment', attack: 5, defense: 5, imageUrl: "https://picsum.photos/seed/equip_omni/200/200" },
  { id: 4016, name: "Deluminator", description: "Sucks light from the room.", price: 1000, type: 'equipment', attack: 0, defense: 50, imageUrl: "https://picsum.photos/seed/equip_deluminator/200/200" },
  { id: 4017, name: "Invisibility Cloak", description: "Rare silvery cloak. Renders wearer invisible.", price: 10000, type: 'equipment', attack: 10, defense: 200, imageUrl: "https://picsum.photos/seed/equip_invis/200/200" },
  { id: 4018, name: "Time-Turner", description: "Hour reversal charm. Handle with care.", price: 15000, type: 'equipment', attack: 50, defense: 150, imageUrl: "https://picsum.photos/seed/equip_time/200/200" },
  { id: 4019, name: "Marauder's Map", description: "Shows everyone in Hogwarts.", price: 3000, type: 'equipment', attack: 20, defense: 80, imageUrl: "https://picsum.photos/seed/equip_map/200/200" },
  { id: 4020, name: "Monster Book of Monsters", description: "Stroking the spine calms it.", price: 120, type: 'equipment', attack: 15, defense: 5, imageUrl: "https://picsum.photos/seed/equip_book_monster/200/200" },
  { id: 4021, name: "Advanced Potion Making", description: "Contains notes from the Half-Blood Prince.", price: 200, type: 'equipment', attack: 25, defense: 10, imageUrl: "https://picsum.photos/seed/equip_book_potions/200/200" },
  { id: 4022, name: "History of Magic", description: "By Bathilda Bagshot. Very dry.", price: 60, type: 'equipment', attack: 0, defense: 5, imageUrl: "https://picsum.photos/seed/equip_book_history/200/200" },
  { id: 4023, name: "Hogwarts: A History", description: "Hermione's favorite.", price: 80, type: 'equipment', attack: 0, defense: 10, imageUrl: "https://picsum.photos/seed/equip_book_hog/200/200" },
  { id: 4024, name: "Golden Snitch", description: "Flesh memory. Good luck charm.", price: 500, type: 'equipment', attack: 0, defense: 40, imageUrl: "https://picsum.photos/seed/equip_snitch/200/200" },
  { id: 4025, name: "Bezoar Case", description: "Carrying case for antidotes.", price: 100, type: 'equipment', attack: 0, defense: 30, imageUrl: "https://picsum.photos/seed/equip_bezoar/200/200" },
  { id: 4026, name: "Foe-Glass", description: "Shows enemies when they are close.", price: 600, type: 'equipment', attack: 10, defense: 60, imageUrl: "https://picsum.photos/seed/equip_foeglass/200/200" },
  { id: 4027, name: "Secrecy Sensor", description: "Vibrates when detecting lies.", price: 350, type: 'equipment', attack: 0, defense: 45, imageUrl: "https://picsum.photos/seed/equip_sensor/200/200" },
  { id: 4028, name: "Probity Probe", description: "Detects concealment charms.", price: 400, type: 'equipment', attack: 0, defense: 50, imageUrl: "https://picsum.photos/seed/equip_probe/200/200" },
  { id: 4029, name: "Mokeskin Pouch", description: "Only the owner can get things out.", price: 250, type: 'equipment', attack: 0, defense: 35, imageUrl: "https://picsum.photos/seed/equip_pouch/200/200" },
  { id: 4030, name: "Two-Way Mirror", description: "Communicate with the holder of the other mirror.", price: 500, type: 'equipment', attack: 0, defense: 20, imageUrl: "https://picsum.photos/seed/equip_mirror/200/200" },
  { id: 4031, name: "Pensieve", description: "Review memories.", price: 2000, type: 'equipment', attack: 0, defense: 100, imageUrl: "https://picsum.photos/seed/equip_pensieve/200/200" },
  { id: 4032, name: "Put-Outer", description: "Dumbledore's invention.", price: 1000, type: 'equipment', attack: 0, defense: 40, imageUrl: "https://picsum.photos/seed/equip_putouter/200/200" },
  { id: 4033, name: "Spectrespecs", description: "See wrackspurts.", price: 40, type: 'equipment', attack: 0, defense: 5, imageUrl: "https://picsum.photos/seed/equip_specs/200/200" },
  { id: 4034, name: "Weasley's Wildfire Whiz-bangs", description: "Unstoppable fireworks.", price: 100, type: 'equipment', attack: 40, defense: 0, imageUrl: "https://picsum.photos/seed/equip_bangs/200/200" },
  { id: 4035, name: "Peruvian Instant Darkness Powder", description: "Creates impenetrable darkness.", price: 300, type: 'equipment', attack: 0, defense: 70, imageUrl: "https://picsum.photos/seed/equip_powder/200/200" }
];
